name: alalmiya_g3
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animate_do: ^3.0.2
  flutter_svg: ^2.0.5
  pin_code_fields: ^8.0.1
  flutter_html: ^3.0.0-alpha.5
  image_picker: ^1.0.4
  google_maps_flutter: ^2.3.0
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.3
  url_launcher: ^6.1.11
  maps_launcher: ^2.2.0
  dotted_border: ^2.1.0
  shimmer: ^3.0.0
  lottie: ^2.3.2
  flutter_rating_bar: ^4.0.1
  video_player: ^2.7.2
  kiwi: ^4.1.0
  get_it: ^7.6.0
  dio:
  easy_localization: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lotties/
    - assets/translations/

  fonts:
    - family: Waterfall
      fonts:
        - asset: assets/fonts/Waterfall-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf