class ProductDetailsStates{}


class GetProductDetailsLoadingState extends ProductDetailsStates{}
class GetProductDetailsFailedState extends ProductDetailsStates{}
class GetProductDetailsSuccessState extends ProductDetailsStates{}